'use client'

import {useEffect,useState} from 'react'
import {supabaseBrowser} from '@/lib/supabase'

export default function Settings(){
  const [r,setR]=useState<any>({}),[s,setS]=useState<any>({}),[saved,setSaved]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false)
  useEffect(()=>{(async()=>{const sb=supabaseBrowser();if(!sb)return;const {data:r}=await sb.from('restaurants').select('*').single();setR(r||{});if(r){const {data:s}=await sb.from('restaurant_settings').select('*').eq('restaurant_id',r.id).maybeSingle();setS(s||{})}})()},[])
  const u=(k:string,v:string)=>setS((x:any)=>({...x,[k]:v}))
  async function save(){setError('');if(!r.id||!r.name.trim()){setError('El nombre del restaurante es obligatorio.');return}const sb=supabaseBrowser();if(!sb){setError('Falta configurar Supabase en .env.local.');return}setSaving(true);try{const restaurantResult=await sb.from('restaurants').update({name:r.name.trim()}).eq('id',r.id);if(restaurantResult.error)throw restaurantResult.error;const settingsResult=await sb.from('restaurant_settings').upsert({...s,restaurant_id:r.id});if(settingsResult.error)throw settingsResult.error;setSaved(true);setTimeout(()=>setSaved(false),1800)}catch{setError('No pudimos guardar los cambios. Inténtalo nuevamente.')}finally{setSaving(false)}}
  return <><div className="eyebrow">Perfil</div><h1>Configuración</h1><div className="form-card" style={{maxWidth:760}}><div className="field"><label>Nombre del restaurante</label><input value={r.name||''} onChange={e=>setR({...r,name:e.target.value})} maxLength={120}/></div><div className="field"><label>Descripción</label><textarea value={s.description||''} onChange={e=>u('description',e.target.value)} rows={3} maxLength={300}/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div className="field"><label>Teléfono</label><input value={s.phone||''} onChange={e=>u('phone',e.target.value)} maxLength={40}/></div><div className="field"><label>WhatsApp</label><input value={s.whatsapp||''} onChange={e=>u('whatsapp',e.target.value)} maxLength={40}/></div></div><div className="field"><label>Dirección</label><input value={s.address||''} onChange={e=>u('address',e.target.value)} maxLength={200}/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div className="field"><label>Instagram</label><input value={s.instagram||''} onChange={e=>u('instagram',e.target.value)} maxLength={160}/></div><div className="field"><label>Sitio web</label><input value={s.website||''} onChange={e=>u('website',e.target.value)} maxLength={200}/></div></div>{error&&<p className="error">{error}</p>}<button className="btn btn-primary" onClick={save} disabled={saving}>{saving?'Guardando…':'Guardar cambios'}</button>{saved&&<span className="success" style={{marginLeft:12}}>Guardado ✓</span>}</div></>
}
