'use client'
import {useEffect,useState,useRef} from 'react'
import {supabaseBrowser} from '@/lib/supabase'
import {Search,Stamp,CheckCircle,Gift} from 'lucide-react'

export default function StampPage(){
 const videoRef=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);const [scanning,setScanning]=useState(false);const [card,setCard]=useState<any>(null),[token,setToken]=useState(''),[customer,setCustomer]=useState<any>(null),[cycle,setCycle]=useState<any>(null),[reward,setReward]=useState<any>(null),[error,setError]=useState(''),[msg,setMsg]=useState('')
 useEffect(()=>{(async()=>{const sb=supabaseBrowser();const {data}=await sb.from('loyalty_cards').select('*').eq('status','published').single();setCard(data)})()},[])
 async function loadCustomer(id:string){const sb=supabaseBrowser();const {data:cc}=await sb.from('customer_cards').select('id').eq('customer_id',id).eq('loyalty_card_id',card.id).single();if(cc){const {data:cy}=await sb.from('loyalty_cycles').select('stamps,status').eq('customer_card_id',cc.id).eq('status','active').single();setCycle(cy)}const {data:rw}=await sb.from('rewards').select('id,name,status').eq('customer_id',id).eq('loyalty_card_id',card.id).eq('status','available').order('created_at',{ascending:false}).limit(1).maybeSingle();setReward(rw||null)}
 
 async function scan(){
  const Detector=(window as any).BarcodeDetector;
  if(!Detector){setError('Tu navegador no ofrece lectura de QR por cámara. Usa el campo de token.');return}
  try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}setScanning(true);const detector=new Detector({formats:['qr_code']});const loop=async()=>{if(!videoRef.current||!streamRef.current)return;try{const codes=await detector.detect(videoRef.current);if(codes[0]?.rawValue){setToken(codes[0].rawValue);streamRef.current.getTracks().forEach(t=>t.stop());streamRef.current=null;setScanning(false);return}}catch{}requestAnimationFrame(loop)};loop()}catch{setError('No pudimos abrir la cámara.')}
 }
 async function find(){setError('');setMsg('');if(!card){setError('No hay una tarjeta publicada.');return}const sb=supabaseBrowser();const {data,error}=await sb.from('customers').select('id,name,contact,public_token,status').eq('public_token',token.trim()).single();if(error||!data){setCustomer(null);setError('No encontramos esta tarjeta.');return}if(data.status!=='active'){setError('Esta tarjeta está bloqueada.');return}setCustomer(data);await loadCustomer(data.id)}
 async function add(amount=1){if(!customer||!card)return;const sb=supabaseBrowser();const {data,error}=await sb.rpc('add_stamp',{p_customer_id:customer.id,p_card_id:card.id,p_amount:amount});if(error){setError('No pudimos completar la operación.');return}setMsg(data?.completed?'🎉 Recompensa desbloqueada':'✓ Sello agregado');await loadCustomer(customer.id);setTimeout(()=>setMsg(''),2200)}
 async function redeem(){if(!reward||!customer)return;const sb=supabaseBrowser();const {error}=await sb.rpc('redeem_reward',{p_reward_id:reward.id,p_customer_id:customer.id});if(error){setError('No pudimos canjear la recompensa.');return}setReward(null);setMsg('✓ Recompensa canjeada');setTimeout(()=>setMsg(''),2200)}
 return <><div className="eyebrow">Operación rápida</div><h1>Entregar sello</h1><p className="muted">Escanea el QR del cliente o pega su token público para identificarlo.</p><div className="grid2"><div className="form-card"><h2><Search size={20}/> Identificar cliente</h2><div className="field"><label>Token / QR</label><input autoFocus placeholder="Pega el token del cliente" value={token} onChange={e=>setToken(e.target.value)} onKeyDown={e=>e.key==='Enter'&&find()}/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><button className="btn btn-primary" onClick={find}>Buscar</button><button className="btn btn-secondary" onClick={scan}>📷 Escanear QR</button></div>{scanning&&<video ref={videoRef} playsInline muted style={{width:'100%',borderRadius:14,marginTop:12}}/>}<p className="muted" style={{fontSize:13,marginTop:16}}>La operación real pasa por una función de backend que valida restaurante, cliente, tarjeta y permisos antes de registrar el sello.</p></div>{customer?<div className="panel"><span className="tag">Cliente identificado</span><h2>{customer.name}</h2><p className="muted">{customer.contact||'Sin contacto'}</p><div style={{fontSize:24,fontWeight:900,margin:'22px 0'}}>{cycle?.stamps||0} / {card.stamp_goal}</div><button className="btn btn-primary" style={{width:'100%',fontSize:17}} onClick={()=>add(1)}><Stamp size={19}/> +1 sello</button>{card.stamps_per_purchase>1&&<button className="btn btn-secondary" style={{width:'100%',marginTop:8}} onClick={()=>add(card.stamps_per_purchase)}>+{card.stamps_per_purchase} sellos</button>}{reward&&<div style={{marginTop:18,padding:16,borderRadius:14,background:'var(--brand2)'}}><div className="tag"><Gift size={14}/> Recompensa disponible</div><h3>{reward.name}</h3><button className="btn btn-primary" style={{width:'100%'}} onClick={redeem}>Canjear recompensa</button></div>}</div>:<div className="panel"><div className="empty">Identifica un cliente para continuar.</div></div>}</div>{error&&<div className="toast error">{error}</div>}{msg&&<div className="toast"><CheckCircle size={17}/> {msg}</div>}</>
}
